name: 'Run sqlfluff with reviewdog'
description: '🐶 Run sqlfluff with reviewdog on pull requests to improve code review experience.'
author: 'Alexander Wornast'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'

  ### Flags for reviewdog ###
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''

  ### Flags for dbt ###
  dbt_adapter: 
    description: |
      The dbt adapter is the dialect (e.g. snowflake)
      This will install the correct adapter version of dbt
    default: snowflake
  dbt_adapter_version:
    description: |
      The dbt adapter version
      This may not match the dbt-core version in some cases
    default: 1.7.4
  dbt_core_version: 
    description: |
      As of dbt version 1.8, the dbt-core version will need to be specified
      Henceforth I have added this as an input
    default: 1.7.14
  dbt_project_dir:
    description: This is where your dbt project directory is located
    default: ./testdata/dbt
  dbt_target: 
    description: | 
      The name of the target you need
      Recommend you copy the profiles_linter directory and place this in your dbt project
    default: snowflake

  ### Flags for sqlfluff ###
  sqlfluff_mode:
    description: | 
      fix or lint: 
       - fix shows suggestions of how to fix your code within your PR
       - lint reports violations will only report the violation
    default: lint
  sqlfluff_templater:
    description: templater for the sql, you probably won't need to change this
    default: dbt
  sqlfluff_version:
    description: Version for sqlfluff
    default: 3.0.6

runs:
  using: 'docker'
  image: 'Dockerfile'

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'check'
  color: 'blue'
